version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - IMAP_HOST=imap.mail.me.com
      - IMAP_PORT=993
      - IMAP_USER=
      - IMAP_PASS=
      - JEV_API_KEY=
      - JEV_MODEL=typesafe/jev-1.13
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge